
  apiVersion: v1
  kind: Service
  metadata:
    name: spring-boot-data-mongodb-master
  spec:
    type: NodePort
    selector:
      app: spring-boot-data-mongodb-master
    ports:
      - protocol: TCP
        port: 8080
        nodePort: 30011


    ----

    apiVersion: v1
    kind: Service
    metadata:
      name: spring-boot-data-mongodb-master
    spec:
      type: NodePort
      selector:
        app: spring-boot-data-mongodb-master
      ports:
        - protocol: TCP
          port: 8080
          nodePort: 30011